/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pertemuan4_5;

/**
 *
 * @author USER
 */
public class Lat2_DimasAryasatya extends javax.swing.JFrame {

    /**
     * Creates new form Lat2_DimasAryasatya
     */
    public Lat2_DimasAryasatya() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textFieldInput_DimasAryasatya = new javax.swing.JTextField();
        textFieldOutput_DimasAryasatya = new javax.swing.JTextField();
        jLabel1_DimasAryasatya = new javax.swing.JLabel();
        jLabel2_DimasAryasatya = new javax.swing.JLabel();
        buttonSin_DimasAryasatya = new javax.swing.JButton();
        buttonCos_DimasAryasatya = new javax.swing.JButton();
        buttonTan_DimasAryasatya = new javax.swing.JButton();
        buttonClear_DimasAryasatya = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_DimasAryasatya.setText("INPUT");

        jLabel2_DimasAryasatya.setText("OUTPUT");

        buttonSin_DimasAryasatya.setText("SIN");
        buttonSin_DimasAryasatya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSin_DimasAryasatyaActionPerformed(evt);
            }
        });

        buttonCos_DimasAryasatya.setText("COS");
        buttonCos_DimasAryasatya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCos_DimasAryasatyaActionPerformed(evt);
            }
        });

        buttonTan_DimasAryasatya.setText("TAN");
        buttonTan_DimasAryasatya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTan_DimasAryasatyaActionPerformed(evt);
            }
        });

        buttonClear_DimasAryasatya.setText("CLEAR");
        buttonClear_DimasAryasatya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClear_DimasAryasatyaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonSin_DimasAryasatya)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(buttonCos_DimasAryasatya)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTan_DimasAryasatya)
                        .addGap(18, 18, 18)
                        .addComponent(buttonClear_DimasAryasatya))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1_DimasAryasatya, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2_DimasAryasatya, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldOutput_DimasAryasatya, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(textFieldInput_DimasAryasatya))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1_DimasAryasatya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addComponent(textFieldInput_DimasAryasatya))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_DimasAryasatya, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldOutput_DimasAryasatya, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSin_DimasAryasatya)
                    .addComponent(buttonCos_DimasAryasatya)
                    .addComponent(buttonTan_DimasAryasatya)
                    .addComponent(buttonClear_DimasAryasatya))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double input, output;
    String hasil;
    
    private void buttonCos_DimasAryasatyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCos_DimasAryasatyaActionPerformed
        // TODO add your handling code here:
        input = Double.parseDouble(String.valueOf(textFieldInput_DimasAryasatya.getText()));
        output = Math.cos(input);
        hasil = Double.toString(output);
        textFieldOutput_DimasAryasatya.setText(hasil);
    }//GEN-LAST:event_buttonCos_DimasAryasatyaActionPerformed

    private void buttonSin_DimasAryasatyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSin_DimasAryasatyaActionPerformed
        // TODO add your handling code here:
        input = Double.parseDouble(String.valueOf(textFieldInput_DimasAryasatya.getText()));
        output = Math.sin(input);
        hasil = Double.toString(output);
        textFieldOutput_DimasAryasatya.setText(hasil);
    }//GEN-LAST:event_buttonSin_DimasAryasatyaActionPerformed

    private void buttonTan_DimasAryasatyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTan_DimasAryasatyaActionPerformed
        // TODO add your handling code here:
        input = Double.parseDouble(String.valueOf(textFieldInput_DimasAryasatya.getText()));
        output = Math.tan(input);
        hasil = Double.toString(output);
        textFieldOutput_DimasAryasatya.setText(hasil);
    }//GEN-LAST:event_buttonTan_DimasAryasatyaActionPerformed

    private void buttonClear_DimasAryasatyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClear_DimasAryasatyaActionPerformed
        // TODO add your handling code here:
        textFieldInput_DimasAryasatya.setText("");
        textFieldOutput_DimasAryasatya.setText("");
    }//GEN-LAST:event_buttonClear_DimasAryasatyaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lat2_DimasAryasatya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lat2_DimasAryasatya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lat2_DimasAryasatya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lat2_DimasAryasatya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lat2_DimasAryasatya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear_DimasAryasatya;
    private javax.swing.JButton buttonCos_DimasAryasatya;
    private javax.swing.JButton buttonSin_DimasAryasatya;
    private javax.swing.JButton buttonTan_DimasAryasatya;
    private javax.swing.JLabel jLabel1_DimasAryasatya;
    private javax.swing.JLabel jLabel2_DimasAryasatya;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFieldInput_DimasAryasatya;
    private javax.swing.JTextField textFieldOutput_DimasAryasatya;
    // End of variables declaration//GEN-END:variables
}
